
substitutions:
  name: 4chrelay
  mqtt_path: homeassistant/switch/${name}

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: -200
    then:
      - delay: 1s
      - mqtt.publish_json:
          topic: "${mqtt_path}/relay-a/config"
          retain: True
          payload: |-
            root["name"] = "relay-a";
            root["icon"] = "mdi:electric-switch";
            root["state_topic"] = "${mqtt_path}/relay-a/state";
            root["command_topic"] = "${mqtt_path}/relay-a/command";
      - mqtt.publish_json:
          topic: "${mqtt_path}/relay-b/config"
          retain: True
          payload: |-
            root["name"] = "relay-b";
            root["icon"] = "mdi:electric-switch";
            root["state_topic"] = "${mqtt_path}/relay-b/state";
            root["command_topic"] = "${mqtt_path}/relay-b/command";
      - mqtt.publish_json:
          topic: "${mqtt_path}/relay-c/config"
          retain: True
          payload: |-
            root["name"] = "relay-c";
            root["icon"] = "mdi:electric-switch";
            root["state_topic"] = "${mqtt_path}/relay-c/state";
            root["command_topic"] = "${mqtt_path}/relay-c/command";
      - mqtt.publish_json:
          topic: "${mqtt_path}/relay-d/config"
          retain: True
          payload: |-
            root["name"] = "relay-d";
            root["icon"] = "mdi:electric-switch";
            root["state_topic"] = "${mqtt_path}/relay-d/state";
            root["command_topic"] = "${mqtt_path}/relay-d/command";

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "4Chrelay Fallback Hotspot"
    password: "TLnxL5BWoD1Q"

web_server:
  port: 80

captive_portal:

logger:
  baud_rate: 0 #need this to free up UART pins

uart:
  baud_rate: 115200 # speed to STC15L101EW
  tx_pin: GPIO1
  rx_pin: GPIO3


switch:
   - platform: restart
     name: "Restart"

mqtt:
  broker: !secret mqtt_broker
  discovery: False
  on_message:
    - topic: "${mqtt_path}/relay-a/command"
      payload: "ON"
      then:
        - uart.write: [0xA0, 0x01, 0x01, 0xA2]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-a/state"
            payload: "ON"
            retain: True
    - topic: "${mqtt_path}/relay-a/command"
      payload: "OFF"
      then:
        - uart.write: [0xA0, 0x01, 0x00, 0xA1]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-a/state"
            payload: "OFF"
            retain: True
    - topic: "${mqtt_path}/relay-b/command"
      payload: "ON"
      then:
        - uart.write: [0xA0, 0x02, 0x01, 0xA3]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-b/state"
            payload: "ON"
            retain: True
    - topic: "${mqtt_path}/relay-b/command"
      payload: "OFF"
      then:
        - uart.write: [0xA0, 0x02, 0x00, 0xA2]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-b/state"
            payload: "OFF"
            retain: True
    - topic: "${mqtt_path}/relay-c/command"
      payload: "ON"
      then:
        - uart.write: [0xA0, 0x03, 0x01, 0xA4]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-c/state"
            payload: "ON"
            retain: True
    - topic: "${mqtt_path}/relay-c/command"
      payload: "OFF"
      then:
        - uart.write: [0xA0, 0x03, 0x00, 0xA3]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-c/state"
            payload: "OFF"
            retain: True
    - topic: "${mqtt_path}/relay-d/command"
      payload: "ON"
      then:
        - uart.write: [0xA0, 0x04, 0x01, 0xA5]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-d/state"
            payload: "ON"
            retain: True
    - topic: "${mqtt_path}/relay-d/command"
      payload: "OFF"
      then:
        - uart.write: [0xA0, 0x04, 0x00, 0xA4]
        - mqtt.publish:
            topic: "${mqtt_path}/relay-d/state"
            payload: "OFF"
            retain: True

api:
  password: !secret api_password

ota:
  password: !secret ota_password

