esphome:
  name: 4chrelay
  platform: ESP8266
  board: esp01_1m
#  on_boot:
#    then:
#      - mqtt.publish:
#          topic: "homeassistant/status/4chrelay"
#          payload: "STARTING"
#      - delay: 2s
#      - mqtt.publish:
#          topic: "homeassistant/status/4chrelay"
#          payload: "STARTING-2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "4Chrelay Fallback Hotspot"
    password: "TLnxL5BWoD1Q"

web_server:
  port: 80

captive_portal:

logger:
  baud_rate: 0 #need this to free up UART pins

uart:
  baud_rate: 115200 # speed to STC15L101EW
  tx_pin: GPIO1
  rx_pin: GPIO3

# mqtt:
#  broker: 192.168.1.167
#  on_message:
#    - topic: "homeassistant/switch/4chrelay-1/set"
#      payload: "ON"
#      then:
#        - uart.write: [0xA0, 0x01, 0x01, 0xA2]
#        - mqtt.publish:
#            topic: "homeassistant/switch/4chrelay-1/state"
#            payload: "ON"
#    - topic: "homeassistant/switch/4chrelay-1/set"
#      payload: "OFF"
#      then:
#        - uart.write: [0xA0, 0x01, 0x00, 0xA1]
#        - mqtt.publish:
#            topic: "homeassistant/switch/4chrelay-1/state"
#            payload: "OFF"

switch:
   - platform: uart
     name: "A2on"
     data: [0xA0, 0x02, 0x01, 0xA3]
   - platform: uart
     name: "A2off"
     data: [0xA0, 0x02, 0x00, 0xA2]
   - platform: restart
     name: "Restart"



# switch:
#   - platform: uart
#     name: "A1on"
#     data: [0xA0, 0x01, 0x01, 0xA2]
# 
#   - platform: uart
#     name: "A1off"
#     data: [0xA0, 0x01, 0x00, 0xA1]
# 
#   - platform: uart
#     name: "A2on"
#     data: [0xA0, 0x02, 0x01, 0xA3]
# 
#   - platform: uart
#     name: "A2off"
#     data: [0xA0, 0x02, 0x00, 0xA2]
# 
#   - platform: uart
#     name: "A3on"
#     data: [0xA0, 0x03, 0x01, 0xA4]
# 
#   - platform: uart
#     name: "A3off"
#     data: [0xA0, 0x03, 0x00, 0xA3]
# 
#   - platform: uart
#     name: "A4on"
#     data: [0xA0, 0x04, 0x01, 0xA5]
# 
#   - platform: uart
#     name: "A4off"
#     data: [0xA0, 0x04, 0x00, 0xA4]
# 
#   - platform: restart
#     name: "4switch_a Restart"

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

